# 图片生成服务配置
# 请在 Web 界面的"设置"页面中配置 API Key
active_provider: default
providers:
  default:
    api_key: liklik
    base_url: https://flow2aaa.zeabur.app
    endpoint_type: /v1/chat/completions
    high_concurrency: false
    model: gemini-2.5-flash-image-landscape
    short_prompt: false
    type: image_api
    use_sse: true

  google_ai:
    api_key: AIzaSyAH6Ly8Tq-qda00g7Y4A3lYqfYsk4CGKvk
    base_url: https://generativelanguage.googleapis.com/
    high_concurrency: false
    model: gemini-3-pro-image-preview
    short_prompt: true
    type: google_genai
    use_sse: false
