# 文本生成服务配置
# 请在 Web 界面的"设置"页面中配置 API Key
active_provider: default
providers:
  default:
    api_key: "sk-xgykkyxfjoiqezssbnntkrpmekulzaejbenubgfvlxfjnojx"
    base_url: https://api.siliconflow.cn/
    max_output_tokens: 8000
    model: Qwen/Qwen2-7B-Instruct
    temperature: 1
    type: openai_compatible
    endpoint_type: /v1/chat/completions
